# Generated by Django 2.2 on 2019-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('profit', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=200)),
                ('per_share_price', models.CharField(max_length=200)),
                ('number_of_shares', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
                ('dividend_yield', models.CharField(max_length=200)),
                ('day_high', models.CharField(max_length=200)),
                ('day_low', models.CharField(max_length=200)),
                ('day_close', models.CharField(max_length=200)),
                ('book_value', models.CharField(max_length=200)),
            ],
        ),
    ]
