# Generated by Django 2.2 on 2019-09-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190816_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_identifier', models.CharField(max_length=200)),
                ('january', models.CharField(max_length=200)),
                ('febuary', models.CharField(max_length=200)),
                ('march', models.CharField(max_length=200)),
                ('april', models.CharField(max_length=200)),
                ('may', models.CharField(max_length=200)),
                ('june', models.CharField(max_length=200)),
                ('july', models.CharField(max_length=200)),
                ('august', models.CharField(max_length=200)),
                ('september', models.CharField(max_length=200)),
                ('october', models.CharField(max_length=200)),
                ('november', models.CharField(max_length=200)),
                ('december', models.CharField(max_length=200)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.statistic')),
            ],
            options={
                'ordering': ['r_identifier'],
            },
        ),
    ]
